[package]
name = "core-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
server = {path = "crates/server"}
client = {path = "crates/client"}
shared = {path = "crates/shared"}
uuid = "1.17.0"
byteorder = "1.5.0"

[workspace]
members = ["crates/*"]
